# ============================================================
# OUTPUTS
# Used by Ansible to generate inventory
# ============================================================

output "edge_public_ip" {
  description = "Public IP of edge nginx - use this to access the app"
  value       = aws_instance.edge.public_ip
}

output "edge_public_dns" {
  description = "Public DNS of edge nginx"
  value       = aws_instance.edge.public_dns
}

output "blue_private_ip" {
  description = "Private IP of BLUE app server"
  value       = aws_instance.blue.private_ip
}

output "green_private_ip" {
  description = "Private IP of GREEN app server"
  value       = aws_instance.green.private_ip
}

output "db_private_ip" {
  description = "Private IP of PostgreSQL server"
  value       = aws_instance.db.private_ip
}

output "ami_id" {
  description = "Ubuntu 24.04 AMI used (for reference)"
  value       = data.aws_ami.ubuntu.id
}

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

# Generates Ansible inventory automatically after terraform apply
resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory-aws.ini"
  content  = <<-INI
    [edge]
    edge-nginx ansible_host=${aws_instance.edge.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

    [prod]
    prod-vm1-BLUE  ansible_host=${aws_instance.blue.private_ip}
    prod-vm2-GREEN ansible_host=${aws_instance.green.private_ip}

    [db]
    db-postgresql ansible_host=${aws_instance.db.private_ip}

    [prod:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/id_ed25519
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${aws_instance.edge.public_ip}'

    [db:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/id_ed25519
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${aws_instance.edge.public_ip}'
  INI
}


# Generate group_vars/all/main.yml with dynamic IPs
resource "local_file" "group_vars_all" {
  filename = "${path.module}/../ansible/group_vars/all/main.yml"
  content  = <<-YAML
    # Auto-generated by Terraform - do not edit manually
    app_name: silverbank
    app_port: 3000

    # AWS private IPs (auto-updated on every terraform apply)
    blue_app_ip:  "${aws_instance.blue.private_ip}"
    green_app_ip: "${aws_instance.green.private_ip}"
    db_app_ip:    "${aws_instance.db.private_ip}"

    docker_user: ubuntu

    vault_db_user:           "{{ vault_db_user }}"
    vault_db_password:       "{{ vault_db_password }}"
    vault_postgres_password: "{{ vault_postgres_password }}"
  YAML
}

# Generate group_vars/prod.yml with dynamic DB IP
resource "local_file" "group_vars_prod" {
  filename = "${path.module}/../ansible/group_vars/prod.yml"
  content  = <<-YAML
    # Auto-generated by Terraform - do not edit manually
    app_image: "ghcr.io/mariusiordan/silverbank"
    app_tag:   "v1.2"
    app_dir:   /opt/app
    app_port:  3000

    db_host:     "${aws_instance.db.private_ip}"
    db_port:     5432
    db_name:     "appdb"
    db_user:     "{{ vault_db_user }}"
    db_password: "{{ vault_db_password }}"
  YAML
}