# group_vars/db.yml
# Variables only available to the [db] group (db-postgresql VM)
# Change these values before running ansible-playbook

postgres_user:     devop_db       # database username
postgres_password: "changeme"    # database password - change this!
postgres_db:       appdb         # database name
postgres_port:     5432          # default postgres port
postgres_data_dir: /opt/postgres/data  # where postgres stores data on the VM
