# group_vars/prod.yml
# Variables only available to the [prod] group (blue and green VMs)
# Update app_image with your actual Docker image before deploying

frontend_image: "ghcr.io/mariusiordan/silverbank-frontend"
backend_image:  "ghcr.io/mariusiordan/silverbank-backend"
app_tag:        "latest"   # override din pipeline cu -e app_tag=v1.0-prod-...
app_dir:        /opt/app
app_port_frontend: 3000
app_port_backend:  4000

db_host:     "10.10.20.20"
db_port:     5432
db_name:     "appdb"
db_user:     "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"