# ============================================================
# outputs.tf
# Outputs printed after terraform apply
# Also auto-generates Ansible inventory and group_vars
# ============================================================

# ============================================================
# OUTPUTS
# ============================================================

output "edge_elastic_ip" {
  description = "Static public IP for edge-nginx - never changes between destroy/apply"
  value       = aws_eip.edge.public_ip
}

output "blue_private_ip" {
  description = "Private IP of BLUE app server - changes on every destroy/apply"
  value       = aws_instance.blue.private_ip
}

output "green_private_ip" {
  description = "Private IP of GREEN app server - changes on every destroy/apply"
  value       = aws_instance.green.private_ip
}

output "db_private_ip" {
  description = "Private IP of PostgreSQL server - changes on every destroy/apply"
  value       = aws_instance.db.private_ip
}

output "monitoring_private_ip" {
  description = "Private IP of monitoring server - changes on every destroy/apply"
  value       = aws_instance.monitoring.private_ip
}

output "ami_id" {
  description = "Ubuntu 24.04 AMI used - for reference"
  value       = data.aws_ami.ubuntu.id
}

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

# ============================================================
# ANSIBLE INVENTORY
# Auto-generated on every terraform apply
# This solves the IP problem - inventory is always up to date
# ============================================================

resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory-aws.ini"
  content  = <<-INI
    # Auto-generated by Terraform - do not edit manually
    # Every terraform apply rewrites this file with current IPs

    [edge]
    edge-nginx ansible_host=${aws_eip.edge.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

    [prod]
    prod-vm1-BLUE ansible_host=${aws_instance.blue.private_ip}
    prod-vm2-GREEN ansible_host=${aws_instance.green.private_ip}

    [db]
    db-postgresql ansible_host=${aws_instance.db.private_ip}

    [monitoring]
    monitoring-staging ansible_host=${aws_instance.monitoring.private_ip}

    [prod:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/id_ed25519
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${aws_eip.edge.public_ip}'

    [db:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/id_ed25519
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${aws_eip.edge.public_ip}'

    [monitoring:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=~/.ssh/id_ed25519
    ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${aws_eip.edge.public_ip}'
  INI
}

# ============================================================
# ANSIBLE GROUP VARS
# Dynamic IPs injected into Ansible variables
# ============================================================

resource "local_file" "group_vars_all" {
  filename = "${path.module}/../ansible/group_vars/all/main.yml"
  content  = <<-YAML
    # Auto-generated by Terraform - do not edit manually

    app_name: silverbank

    # Ports
    app_port_frontend: 3000
    app_port_backend: 4000

    # Database name (same value used in postgres role and app role)
    db_name: "appdb"

    # IPs - auto-updated on every terraform apply
    edge_ip: "${aws_eip.edge.public_ip}"
    blue_ip: "${aws_instance.blue.private_ip}"
    green_ip: "${aws_instance.green.private_ip}"
    db_ip: "${aws_instance.db.private_ip}"
    monitoring_ip: "${aws_instance.monitoring.private_ip}"

    # Docker user on all VMs
    docker_user: ubuntu

    # Vault references - actual secrets are in vault.yml
    db_user: "{{ vault_db_user }}"
    db_password: "{{ vault_db_password }}"
    postgres_password: "{{ vault_postgres_password }}"
    ghcr_token: "{{ vault_ghcr_token }}"
    jwt_secret: "{{ vault_jwt_secret }}"
    jwt_refresh_secret: "{{ vault_jwt_refresh_secret }}"
  YAML
}

resource "local_file" "group_vars_prod" {
  filename = "${path.module}/../ansible/group_vars/prod.yml"
  content  = <<-YAML
    # Auto-generated by Terraform - do not edit manually

    frontend_image: "ghcr.io/mariusiordan/silverbank-frontend"
    backend_image: "ghcr.io/mariusiordan/silverbank-backend"
    app_tag: "latest"
    app_dir: /opt/app

    db_host: "${aws_instance.db.private_ip}"
    db_port: 5432
    db_name: "appdb"
    db_user: "{{ vault_db_user }}"
    db_password: "{{ vault_db_password }}"
  YAML
}