# group_vars/prod.yml
# Variables only available to the [prod] group (blue and green VMs)
# Update app_image with your actual Docker image before deploying

app_image: "ghcr.io/mariusiordan/silverbank"
app_tag:   "v1.2"
app_dir:   /opt/app
app_port:  3000

# Database connection - AWS private IP
db_host:     "10.0.2.60"
db_port:     5432
db_name:     "appdb"
db_user:     "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
