# group_vars/all/main.yml
# Variables for AWS infrastructure

app_name: silverbank
app_port: 3000

# AWS private IPs (from terraform output)
blue_app_ip:  "10.0.2.204"   # prod-vm1-BLUE
green_app_ip: "10.0.2.249"   # prod-vm2-GREEN
db_app_ip:    "10.0.2.60"    # db-postgresql

docker_user: ubuntu  # AWS Ubuntu default user

# Load secrets from vault
vault_db_user:           "{{ vault_db_user }}"
vault_db_password:       "{{ vault_db_password }}"
vault_postgres_password: "{{ vault_postgres_password }}"